name: Price Check Action
on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install
        run: |
          pip install -r requirements.txt
          playwright install chromium
      - name: Run
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python src/bot.py
      - name: Save DB
        run: |
          git config --global user.name "PriceBot"
          git config --global user.email "bot@github.com"
          git add data/prices.db
          git commit -m "Update history [skip ci]" || exit 0
          git push